language: node_js
node_js:
  - "4"
after_success:
  - npm run coveralls
  - curl --data build=true -X POST https://registry.hub.docker.com/u/telemark/tfk-saksbehandling-queue-pull/trigger/0805bc8f-e8ae-4153-81be-2bd6403a6f26/